{% set version = "0.1.3" %}
{% set sha256 = "ca917916c1ba8beadff52946076ebb5c065a111d67895fb31efdf97fa70ab3e3" %}

package:
  name: ipyx
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/i/ipyx/ipyx-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
    - nodejs
    - yarn
    - jupyterlab =3
    - jupyter-packaging
  run:
    - python >=3.6
    - ipywidgets >=7.0.0

test:
  imports:
    - ipyx
  commands:
    - test -f ${PREFIX}/share/jupyter/nbextensions/ipyx/extension.js                             # [unix]
    - test -f ${PREFIX}/share/jupyter/nbextensions/ipyx/index.js                                 # [unix]
    - test -f ${PREFIX}/share/jupyter/labextensions/ipyx/package.json                            # [unix]
    - if not exist %PREFIX%\\share\\jupyter\\nbextensions\\ipyx\\extension.js (exit 1)           # [win]
    - if not exist %PREFIX%\\share\\jupyter\\nbextensions\\ipyx\\index.js (exit 1)               # [win]
    - if not exist %PREFIX%\\share\\jupyter\\labextensions\\ipyx\\package.json (exit 1)          # [win]

about:
  home: https://github.com/davidbrochart/ipyx
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: A Jupyter widget library for reactive variables
  doc_url: https://github.com/davidbrochart/ipyx
  dev_url: https://github.com/davidbrochart/ipyx

extra:
  recipe-maintainers:
    - davidbrochart
